services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    restart: always
    working_dir: /var/www
    volumes:
      - ./backend:/var/www
    depends_on:
      - database
    command: bash -c "until php artisan migrate --force; do echo 'Esperando o banco de dados...'; sleep 5; done && php-fpm"


  web:
    image: nginx:alpine
    container_name: web
    restart: always
    ports:
      - "8000:80"
    volumes:
      - ./backend:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend

  database:
    image: mysql:8
    container_name: database
    restart: always
    environment:
      MYSQL_DATABASE: desafio
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile  
    container_name: frontend
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "8080:8080"
    command: ["npm", "run", "serve"] 
    depends_on:
      - backend
      - database

volumes:
  dbdata:
